/*
    Copyright 2019 Brian Alexander

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

*/

package edu.cnm.deepdive.picturequest.model.entity;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.ForeignKey;
import androidx.room.PrimaryKey;
import com.google.gson.annotations.SerializedName;

/**
 * This class is an {@link Entity} class for the {@link androidx.room.RoomDatabase} specifically for
 * helping {@link edu.cnm.deepdive.picturequest.service.ClarifaiTask} find. matches more easily with {@link Choice}
 * this is done by presenting synonyms for some of the objects/tags Clarifai may add to {@link Input}.
 * The {@link Entity} has a {@link ForeignKey} to {@link Choice} by its id.
 *
 * @author Brian Alexander
 */
@Entity(
    foreignKeys = {
        @ForeignKey(entity = Choice.class,
            parentColumns = "id",
            childColumns = "choice_id",
            onDelete = ForeignKey.CASCADE)
    }
    )
public class ChoiceSynonym {

  /**
   * Id of each {@link ChoiceSynonym} autogenerated by {@link androidx.room.Room}
   */
  @PrimaryKey(autoGenerate = true)
  private long id;
  /**
   * The actual synonym to a {@link Choice} as a {@link String}
    */
  private String name;
  /**
   * What {@link Choice} the {@link ChoiceSynonym} relates to by its id.
   */
  @SerializedName("to")
  @ColumnInfo(name="choice_id", index = true)
  private long choiceId;

  /**
   * Gets the id for the {@link ChoiceSynonym}
   * @return the id
   */
  public long getId() {
    return id;
  }

  /**
   * Sets an id for a {@link ChoiceSynonym}
   * @param id the id to set to
   */
  public void setId(long id) {
    this.id = id;
  }

  /**
   * get the id of the {@link Choice} associated to synonym
   * @return
   */
  public long getChoiceId() {
    return choiceId;
  }

  /**
   * set the {@link Choice} for a {@link ChoiceSynonym}
   * @param choiceId
   */
  public void setChoiceId(long choiceId) {
    this.choiceId = choiceId;
  }

  /**
   * Get the name of the {@link ChoiceSynonym}
   * @return the name as a {@link String}
   */
  public String getName() {
    return name;
  }

  /**
   * Set the name of a {@link ChoiceSynonym}
   * @param name the name as a {@link String}
   */
  public void setName(String name) {
    this.name = name;
  }

}
