/*
    Copyright 2019 Brian Alexander

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

*/

package edu.cnm.deepdive.picturequest.model.entity;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.ForeignKey;
import androidx.room.Index;
import androidx.room.PrimaryKey;
import com.google.gson.annotations.SerializedName;


/**
 * This class is an {@link Entity} class for the {@link androidx.room.RoomDatabase} specifically for the
 * avaiable choices for the 'choose' your own adventure game. The {@link Entity} has {@link ForeignKey}
 * to the {@link Scene} specifically, what {@link Scene} the {@link Choice} comes from and leads to.
 * @author Brian Alexander
 */
@Entity(
    indices = {
        @Index(value = {"from_scene_id","name"}, unique = true)},
    foreignKeys = {
        @ForeignKey(entity = Scene.class,
            parentColumns = "id",
            childColumns = "from_scene_id",
            onDelete = ForeignKey.CASCADE),
        @ForeignKey(entity = Scene.class,
            parentColumns = "id",
            childColumns = "to_scene_id",
            onDelete = ForeignKey.CASCADE)
    }
    )
public class Choice {

  /**
   * Id for the {@link Choice} generated by {@link androidx.room.Room}
   */
  @PrimaryKey(autoGenerate = true)
  private long id;

  /**
   * The name of the Choice as a {@link String}
   */
  @ColumnInfo(collate = ColumnInfo.NOCASE)
  private String name;

  /**
   * What {@link Scene} the {@link Choice} comes from
   */
  @ColumnInfo(name = "from_scene_id", index = true)
  @SerializedName("from")
  private long fromSceneId;

  /**
   * What {@link Scene} the {@link Choice} comes from
   *
   */
  @SerializedName("to")
  @ColumnInfo(name = "to_scene_id", index = true)
  private long toSceneId;

  /**
   * Gets the {@link Scene} id the {@link Choice} is going to
   * @return a long that is the {@link Scene} id
   */
  public long getToSceneId() {
    return toSceneId;
  }

  /**
   * sets the {@link Scene} id the {@link Choice} is going to
   * @param toSceneId a long that is the {@link Scene} id
   */
  public void setToSceneId(long toSceneId) {
    this.toSceneId = toSceneId;
  }

  /**
   * Gets the {@link Scene} id the {@link Choice} is coming from
   * @return a long that is the {@link Scene} id
   */
  public long getFromSceneId() {
    return fromSceneId;
  }

  /**
   * sets the {@link Scene} id the {@link Choice} is coming from
   * @param fromSceneId a long that is the {@link Scene} id
   */
  public void setFromSceneId(long fromSceneId) {
    this.fromSceneId = fromSceneId;
  }

  /**
   * gets the Id of a {@link Choice}
   * @return long of the {@link #id}
   */
  public long getId() {
    return id;
  }

  /**
   * Gets the name of a {@link Choice}
   * @return the name as a {@link String}
   */
  public String getName() {
    return name;
  }

  /**
   * Sets a {@link Choice} id
   * @param id a long to set the id to
   */
  public void setId(long id) {
    this.id = id;
  }

  /**
   * Sets a {@link Choice} name
   * @param name what to set the name to
   */
  public void setName(String name) {
    this.name = name;
  }

  /**
   * override of to string to make sure it is simply outputting the name of the {@link Choice}
   * @return {@link String} of the {@link #name}
   */
  @Override
  public String toString() {
    return name;
  }
}
