/*
    Copyright 2019 Brian Alexander

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

*/

package edu.cnm.deepdive.picturequest.model.entity;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.ForeignKey;
import androidx.room.Index;
import androidx.room.PrimaryKey;

/**
 * This class is an {@link Entity} class for the {@link androidx.room.RoomDatabase} specifically for the
 * player in our game. The {@link Entity} has {@link ForeignKey}
 * to the {@link Scene} specifically, what {@link Scene} the {@link Player} is at.
 * @author Brian Alexander
 */
@Entity(
    foreignKeys = {
        @ForeignKey(entity = Scene.class,
            parentColumns = "id",
            childColumns = "scene_id",
            onDelete = ForeignKey.RESTRICT
        )
    },
    indices = {
        @Index(value = "authentication_id", unique = true)
    }
)
public class Player {

  /**
   * The id of the player autogenerated by {@link androidx.room.Room}
   */
  @PrimaryKey(autoGenerate = true)
  private long id;
  /**
   * The authentication id from Google gotten from {@link edu.cnm.deepdive.picturequest.service.GoogleSignInService} to help us create a unique id.
   */
  @ColumnInfo(name = "authentication_id")
  private String authenticationId;
  /**
   * Name of the player gotten through {@link edu.cnm.deepdive.picturequest.service.GoogleSignInService} from their profile.
   */
  private String player;
  /**
   * The id of the {@link Scene} the {@link Player} is currently at.
   */
  @ColumnInfo(name = "scene_id", index = true)
  private long sceneId;

  /**
   * Method to get the id of the {@link Scene} associated to the {@link Player}
   * @return
   */
  public long getSceneId() {
    return sceneId;
  }

  /**
   * Method to set the id of the {@link Scene} associated to the {@link Player}
   * @param sceneId the id of the {@link Scene} to set to
   */
  public void setSceneId(long sceneId) {
    this.sceneId = sceneId;
  }

  /**
   * Method to get the id of the Player
   * @return the id as a long
   */
  public long getId() {
    return id;
  }

  /**
   * Method to set the id
   * @param id what to set the id to
   */
  public void setId(long id) {
    this.id = id;
  }

  /**
   * method to get the name of the Player
   * @return the name
   */
  public String getPlayer() {
    return player;
  }

  /**
   * Method to set the name of the player
   * @param player what to set it to
   */
  public void setPlayer(String player) {
    this.player = player;
  }

  /**
   * Method to get the AuthId created in {@link edu.cnm.deepdive.picturequest.service.GoogleSignInService}
   * @return the AuthId
   */
  public String getAuthenticationId() {
    return authenticationId;
  }

  /**
   * Method that should never be used to set the AuthId yourself
   * @param authenticationId what to set it to
   */
  public void setAuthenticationId(String authenticationId) {
    this.authenticationId = authenticationId;
  }
}
